name: File Changes
on: push
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Files Changed
        uses: know-ops/files-changed-action@v1-alpha.12
