name: File Changes
on: push
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkouts@v2
      - name: Files Changed
        uses: know-ops/files-changed@v1
